---

- name: shutdown database
  shell: >
    printf 'shutdown immediate;\n' | $ORACLE_HOME/bin/sqlplus / as sysdba
  environment:
    ORACLE_HOME: "{{ psbp_oracle_home }}"
    ORACLE_BASE: "{{ psbp_oracle_base }}"
    ORACLE_SID: "{{psbp_db_name }}"
  become_user: "{{ psbp_oracle_user }}"
  ignore_errors: true
