# SBP Files Directory
SBP_files_source: /log/viniciusdba/Ansible/SBP_Patching_Files

# Patch related files
SBP_Files:
  - { sbp_patch_number: '31511219', sbp_patch_file: 'SAP121XSP_2011-20012300.ZIP', sbp_dbbp_patch_file: 'PROACTIVEBP121XSP_2011-20012300.ZIP', sbp_opatch_file: 'OPATCH121XSP_2011-20012319.ZIP', sbp_month_year: 'NOV_2020' , sbp_patch_name: 'SBP_12102201020_202011', sbp_post_install_sql: 'post-install.sql' }
  - { sbp_patch_number: '31965033', sbp_patch_file: 'SAP121XSP_2102-20012300.ZIP', sbp_dbbp_patch_file: 'PROACTIVEBP121XSP_2102-20012300.ZIP', sbp_opatch_file: 'OPATCH121XSP_2102-20012300.ZIP', sbp_month_year: 'FEB_2021' , sbp_patch_name: 'SBP_12102210119_202102', sbp_post_install_sql: 'post-install.sql' }

# Variables for Hosts to have patch applied
SBP_Hosts:
  - { sbp_hostname: 'XXXDB1', sbp_oracle_user: 'ora1', sbp_db_name: 'DB1', sbp_listener_name: 'LISTENER_DB1', sbp_oracle_home: '/oracle/DB1/121', sbp_oracle_base: '/oracle/DB1/saptrace' }
  - { sbp_hostname: 'XXXDB2', sbp_oracle_user: 'ora2', sbp_db_name: 'DB2', sbp_listener_name: 'LISTENER_DB2', sbp_oracle_home: '/oracle/DB2/121', sbp_oracle_base: '/oracle/DB2/saptrace' }
  - { sbp_hostname: 'XXXDB3', sbp_oracle_user: 'ora3', sbp_db_name: 'DB3', sbp_listener_name: 'LISTENER_DB3', sbp_oracle_home: '/oracle/DB3/121', sbp_oracle_base: '/oracle/DB3/saptrace' }
  
# Global Actions | Valid values for ga_sbp_action: 'Pollback' or 'Apply'
ga_sbp_patch_number: '31511219'


# Veritas Group Name
veritas_group_name: ORA_1
